deriv-com/sinbad

gatsby-node.js, src/pages/job-description/[id].tsx
=> Prince/ add dynamic page for job-description

src/components/layout/header.tsx, src/pages/open-positions/open-positions.tsx
=> Vijayasree/ fix: fixed containers in open positions

src/components/elements/button.tsx, src/components/layout/header.tsx
Changes:
-   burger menu in header
-   [x] New feature
=> Feature Hamburger menu for mobile response 

src/pages/careers/index.tsx, src/pages/index.tsx, src/pages/job-description/[id].tsx, src/pages/open-positions/index.tsx
=> Vijayasree/feat: add title tag to all the pages

src/common/utility.js, src/components/layout/join-us/career.tsx, src/components/layout/join-us/home.tsx, src/components/layout/join-us/job.tsx
=> Vijayasree/feat: redirection to open pages on click button

src/themes/global-style.ts, static/css/ibm-plex-sans-var.css
=> style: remove unused font family

src/components/elements/button.tsx, src/components/layout/join-us/home.tsx, src/pages/open-positions/open-positions.tsx
=> Vijayasree/fix: mobile responsiveness in open positions and join us

src/pages/home/carousel.tsx
=> Vijayasree/ fix: carousel height and autoplay time

src/pages/careers/hiring-process.tsx
=> Vijayasree/text: interview with COO/CTO/CEO section content mistake

src/pages/careers/work-with-us.tsx
Changes:
-   fix color of header text
=> Difference in main banner text color 

src/components/containers/table.tsx, src/pages/careers/perks-benefits.tsx
Changes:
-   update design to perks and benefits
=> Perks and Benefits section is not as per the design 

src/components/layout/header.tsx
Changes:
-    update active link in header
=> Header menu is not highlighted when we paste and load the url in browser

src/components/containers/common/style.ts, src/components/layout/footer/social-wrapper.tsx
Changes:
-   update footer info
=> update footer info

src/components/layout/header.tsx
=> Vijayasree/fix: hamburger menu improvements

src/components/containers/common/style.ts, src/components/layout/footer.tsx, src/components/layout/footer/social-wrapper.tsx, src/components/layout/join-us/career.tsx, src/components/layout/join-us/home.tsx, src/components/layout/join-us/job.tsx, src/components/layout/join-us/open-position.tsx, src/pages/careers/perks-benefits.tsx, src/pages/home/our-terms.tsx, src/pages/home/welcome.tsx, static/css/global-style.css, static/css/ibm-plex-sans-var.css
Changes:
-   update footer by design and make join us unbold
=> Difference in design compared to figma 

src/pages/job-description/benefits.tsx, src/pages/job-description/description.tsx
=> Vijayasree/fix: issues in jd page

src/pages/open-positions/open-positions.tsx
=> Vijayasree/fix: improvements in open positions page

src/data/positions.json
=> Software tester JD page & WinOps Engineers JD page have deriv.com mentioned 

src/data/positions.json, src/pages/job-description/data.ts, src/pages/job-description/job-title.tsx, src/pages/open-positions/open-positions.tsx
Changes:
-   change text, id and slug of jd data
=> Grammar mistakes in Open position JD description.

src/pages/careers/hiring-process.tsx
=> Aswathy/fix: icon change fix issue

src/pages/careers/hiring-process.tsx, src/pages/careers/open-positions.tsx, src/pages/careers/why-with-us.tsx
=> Spelling error in career page 

src/pages/home/tech-stack.tsx
=> Content change

src/pages/careers/open-positions.tsx
Changes:
-   make see jobs bold
=> "SEE JOBS" link is not in bold  

src/pages/careers/hiring-process.tsx
Changes:
-   update section in hirign process component
=> "Interview with HR and Manager" section content is incomplete

src/common/os-detect.js, src/components/layout/footer/social-wrapper.tsx
=> Revert "Vijayasree/feat: add open dialer for phone and google maps for address in footer"

src/components/layout/header.tsx, src/components/layout/join-us/career.tsx, src/components/layout/join-us/home.tsx, src/components/layout/join-us/job.tsx, src/components/layout/join-us/open-position.tsx, src/pages/careers/perks-benefits.tsx, src/pages/home/carousel.tsx, src/pages/home/our-terms.tsx
=> Vijayasree/fix: remove repeated sinbad

src/pages/home/welcome.tsx
Changes:
-   ...
-   [x] Refactor code
=> Spelling mistake - (standards)

src/pages/home/tech-stack.tsx
Changes:
-    tech stack styles
=> NikitK/ Tech stack section alignment and font change

static/css/ibm-plex-sans-var.css
=> Vijayasree/fix: removing .eot font format

src/pages/careers/work-with-us.tsx
Changes:
-   extra space and padding in title work-with-us
=> NikitK/ Extra space in main banner image text 

src/components/layout/header.tsx
Changes:
-   make header title hover
=> NikitK/ Hover icon is not showing for website header "Sinbad Software" 

src/pages/home/tech-stack.tsx
Changes:
-   remove repeatable label
=> NikitK/ Removal of repeated "sinbad software" text - homepage

src/pages/job-description/description.tsx
=> style: reduce space between paragraphs

src/data/positions.json, src/pages/job-description/job-title.tsx
=> Al-amin/Responsive : JD page - Few titles are not center aligned. 

src/components/layout/header.tsx
Changes:
-   ...
-   [x] Refactor code
=> Al-amin/added contact us on mobile side bar

src/common/os-detect.js, src/components/layout/footer/social-wrapper.tsx
=> Vijayasree/feat: appropriate links for footer icons

src/components/containers/table.tsx, src/data/positions.json, src/pages/careers/hiring-process.tsx, src/pages/careers/perks-benefits.tsx, src/pages/careers/work-with-us.tsx, src/pages/home/our-terms.tsx, src/pages/open-positions/open-positions.tsx
=> Vijayasree/ Proof reading

src/pages/careers/hiring-process.tsx, src/pages/careers/open-positions.tsx, src/pages/careers/perks-benefits.tsx
Changes:
-   increase card height and fix mistake in word
=> NikitK/ Career page-issues 

src/pages/home/carousel.tsx
Changes:
-   align text in home carousel and remove max width for img for mobile
=> NikitK/ Change of Text alignment and removal of big padding  in responsive mode/mobile

src/common/constants.ts, src/common/utility.js, src/components/layout/footer/social-wrapper.tsx
=> Vijayasree/fix: incorrect email in contact us

src/pages/home/tech-stack.tsx
Changes:
-   cropped text in tech stack in homepage
=> NikitK/ Homepage - Tech stack is cropped on mobile 

src/pages/home/carousel.tsx
=> Vijayasree/fix: carousel height in tablet

src/components/layout/join-us/open-position.tsx, src/pages/open-positions/open-positions.tsx
Changes:
-   remove section in open positions
=> NikitK/ Remake open positions page

src/pages/job-description/benefits.tsx
=> Vijayasree/fix: benefits header in mobile

src/pages/job-description/benefits.tsx
=> style: fixed location style on job description

src/components/layout/join-us/career.tsx, src/components/layout/join-us/home.tsx, src/components/layout/join-us/job.tsx, src/components/layout/join-us/open-position.tsx, src/pages/careers/hiring-process.tsx, src/pages/careers/why-with-us.tsx, src/pages/careers/work-with-us.tsx, src/themes/device.ts
=> Vijayasree/fix: careers page responsiveness and carousel height for tablet

.circleci/config.yml
- Clean CircleCI config
-   [x] Script configuration
=> Clean CircleCI config

src/common/constants.ts, src/components/layout/footer/social-wrapper.tsx
=> Aswathy/fix: updated the phone number and email

src/components/layout/footer/social-wrapper.tsx
=> Aswathy/fix: css minimum width fix

src/components/containers/common/style.ts, src/components/layout/footer/social-wrapper.tsx
=> Aswathy/fix: added width for social wrapper

src/common/storage.js
**Description:**
This enhancement focuses on refining the host validation mechanism within the `CookieStorage` module to bolster its reliability and resilience. The update ensures that host checks are performed rigorously, enhancing the module's ability to handle various input scenarios effectively.
**Changes Included:**
- Strengthened the host validation logic to ensure accurate identification and verification of trusted hosts.
- Implemented a more robust approach to host checking, leveraging explicit whitelisting of allowed hosts for improved security and control.
```javascript
// Previous host validation logic
const is_deriv_com = String(hostname).includes('deriv.com');
const is_binary_sx = String(hostname).includes('binary.sx');
// Updated host validation logic
let allowedHosts = …
```
=> Enhancement: Improve host checks

package-lock.json, package.json
Upgrades the webpack version to fix the issues.
=> Upgrade webpack version

.github/actions/publish_to_pages_production/action.yml, vercel.dr.json
=> Ako/ update the output dir

.github/CODEOWNERS, package.json
Changes:
-   update binary-com to deriv-com
=> behnaz/FEQ-2092/binary-com to deriv-com
